### PR TITLE
Update Crossbeam to v1

### PR DESCRIPTION
**Pull request by igorschechtel**
<details>
  <summary>📦 Published PR as canary version: <code>Canary Versions</code></summary>
  <br />

  :sparkles: Test out this PR locally via:
  
  ```bash
  npm install @friggframework/api-module-crossbeam@1.0.1-canary.9.67e3367.0
  # or 
  yarn add @friggframework/api-module-crossbeam@1.0.1-canary.9.67e3367.0
  ```
</details>

### CODE REVIEW

**Review by leofmds — APPROVED** [review]
LGTM

**Comment by seanspeaks** [comment]
:rocket: PR was released in [`@friggframework/api-module-42matters@2.0.0-next.0`](https://github.com/friggframework/api-module-library/releases/tag/%40friggframework/api-module-42matters%402.0.0-next.0), [`@friggframework/api-module-asana@2.0.0-next.0`](https://github.com/friggframework/api-module-library/releases/tag/%40friggframework/api-module-asana%402.0.0-next.0), [`@friggframework/api-module-connectwise@2.0.0-next.0`](https://github.com/friggframework/api-module-library/releases/tag/%40friggframework/api-module-connectwise%402.0.0-next.0), [`@friggframework/api-module-contentful@2.0.0-next.0`](https://github.com/friggframework/api-module-library/releases/tag/%40friggframework/api-module-contentful%402.0.0-next.0), [`@friggframework/api-module-contentstack@2.0.0-next.0`](https://github.com/friggframework/api-module-library/releases/tag/%40friggframework/api-module-contentstack%402.0.0-next.0), [`@friggframework/api-module-crossbeam@2.0.0-next.0`](https://github.com/friggframework/api-module-library/releases/tag/%40friggframework/api-module-crossbeam%402.0.0-next.0), [`@friggframework/api-module-deel@2.0.0-next.0`](https://github.com/friggframework/api-module-library/releases/tag/%40friggframework/api-module-deel%402.0.0-next.0), [`@friggframework/api-module-frontify@2.0.0-next.0`](https://github.com/friggframework/api-module-library/releases/tag/%40friggframework/api-module-frontify%402.0.0-next.0), [`@friggframework/api-module-google-calendar@2.0.0-next.0`](https://github.com/friggframework/api-module-library/releases/tag/%40friggframework/api-module-google-calendar%402.0.0-next.0), [`@friggframework/api-module-google-drive@2.0.0-next.0`](https://github.com/friggframework/api-module-library/releases/tag/%40friggframework/api-module-google-drive%402.0.0-next.0), [`@friggframework/api-module-helpscout@1.0.0-next.0`](https://github.com/friggframework/api-module-library/releases/tag/%40friggframework/api-module-helpscout%401.0.0-next.0), [`@friggframework/api-module-hubspot@2.0.0-next.0`](https://github.com/friggframework/api-module-library/releases/tag/%40friggframework/api-module-hubspot%402.0.0-next.0), [`@friggframework/api-module-ironclad@2.0.0-next.0`](https://github.com/friggframework/api-module-library/releases/tag/%40friggframework/api-module-ironclad%402.0.0-next.0), [`@friggframework/api-module-linear@2.0.0-next.0`](https://github.com/friggframework/api-module-library/releases/tag/%40friggframework/api-module-linear%402.0.0-next.0), [`@friggframework/api-module-microsoft-teams@2.0.0-next.0`](https://github.com/friggframework/api-module-library/releases/tag/%40friggframework/api-module-microsoft-teams%402.0.0-next.0), [`@friggframework/api-module-salesforce@2.0.0-next.0`](https://github.com/friggframework/api-module-library/releases/tag/%40friggframework/api-module-salesforce%402.0.0-next.0), [`@friggframework/api-module-slack@2.0.0-next.0`](https://github.com/friggframework/api-module-library/releases/tag/%40friggframework/api-module-slack%402.0.0-next.0), [`@friggframework/api-module-stripe@2.0.0-next.0`](https://github.com/friggframework/api-module-library/releases/tag/%40friggframework/api-module-stripe%402.0.0-next.0), [`@friggframework/api-module-unbabel-projects@2.0.0-next.0`](https://github.com/friggframework/api-module-library/releases/tag/%40friggframework/api-module-unbabel-projects%402.0.0-next.0), [`@friggframework/api-module-unbabel@2.0.0-next.0`](https://github.com/friggframework/api-module-library/releases/tag/%40friggframework/api-module-unbabel%402.0.0-next.0), [`@friggframework/api-module-zoho-crm@2.0.0-next.0`](https://github.com/friggframework/api-module-library/releases/tag/%40friggframework/api-module-zoho-crm%402.0.0-next.0), [`@friggframework/api-module-zoom@2.0.0-next.0`](https://github.com/friggframework/api-module-library/releases/tag/%40friggframework/api-module-zoom%402.0.0-next.0) :rocket:

**Comment by seanspeaks** [comment]
:rocket: PR was released in [`@friggframework/api-module-salesforce@2.0.0-next.1`](https://github.com/friggframework/api-module-library/releases/tag/%40friggframework/api-module-salesforce%402.0.0-next.1) :rocket:

**Comment by seanspeaks** [comment]
:rocket: PR was released in [`@friggframework/api-module-hubspot@2.0.0-next.4`](https://github.com/friggframework/api-module-library/releases/tag/%40friggframework/api-module-hubspot%402.0.0-next.4) :rocket:

**Pull request merged**
