### PR TITLE
Add API module for Asana

### PR DESCRIPTION
**Pull request by igorschechtel**

### CODE REVIEW

**Review by leofmds — APPROVED** [review]
LGTM

**Review by MichaelRyanWebber — APPROVED** [review]
Excellent work! Happy to see the mock based `testAutherDefinition` being used!

**Comment by seanspeaks** [comment]
:rocket: PR was released in [`@friggframework/api-module-asana@1.1.4`](https://github.com/friggframework/api-module-library/releases/tag/%40friggframework/api-module-asana%401.1.4), [`@friggframework/api-module-unbabel-projects@1.0.1`](https://github.com/friggframework/api-module-library/releases/tag/%40friggframework/api-module-unbabel-projects%401.0.1), [`@friggframework/api-module-unbabel@1.1.3`](https://github.com/friggframework/api-module-library/releases/tag/%40friggframework/api-module-unbabel%401.1.3), [`@friggframework/api-module-zoho-crm@1.0.1`](https://github.com/friggframework/api-module-library/releases/tag/%40friggframework/api-module-zoho-crm%401.0.1) :rocket:

**Comment by seanspeaks** [comment]
:rocket: PR was released in [`@friggframework/api-module-hubspot@1.1.6`](https://github.com/friggframework/api-module-library/releases/tag/%40friggframework/api-module-hubspot%401.1.6), [`@friggframework/api-module-salesforce@1.0.1`](https://github.com/friggframework/api-module-library/releases/tag/%40friggframework/api-module-salesforce%401.0.1), [`@friggframework/api-module-unbabel@1.1.4`](https://github.com/friggframework/api-module-library/releases/tag/%40friggframework/api-module-unbabel%401.1.4) :rocket:

**Pull request merged**
